### ISSUE TITLE
tripaldock self update does not accept no for an answer for replacing the docker-compose

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripaldock#23]
```
TRIPALDOCK: Copying new files
TRIPALDOCK: Initializing ...
TRIPALDOCK: Done. You may use the local version of tripaldock directly from this folder ./tripaldock COMMAND
TRIPALDOCK: Would you like to replace your docker-compose.yaml file with a new one?
1) Yes
2) No
#? 2

#?
1) Yes
2) No
#? 2

#?
1) Yes
2) No
#? 1

```

**Comment by almasaeed2010** [comment]
There isn't really a need for updating docker-compose since chances are it would mess up your ports setup (tripaldock issues port numbers automatically based on what's available). I don't wanna read your compos yaml file just to figure out what should change. So removing this option and maybe directing the user to update their yaml files is a better solution for the time being.
